SNS topic for reports
USSBA/terraform-aws-inspector pull request #5
Opened 2019-12-21 23:11 UTC by airmonitor

- Added SNS topic for sending Inspector reports to subscribers. Next PR will contain integration with https://github.com/awslabs/amazon-inspector-finding-forwarder

- Ruleset arn's moved to separate dict in locals, this way we can select particular arn based on region provided by data "aws_region"

2020-01-27 11:46 UTC, FnTm commented
@airmonitor Thank you for this addition! I'd be really interested in using this. Do you maybe have any idea on who we should ping to get this pr reviewed and moving again?

2020-07-01 19:39 UTC, bushong1 requested changes
All the SNS Topic subscription features really feels like an external module to me.

We're happy to accept changes to the ARN lists, as well as exporting any resources you need to access.

2020-07-01 19:39 UTC, bushong1 commented on main.tf
> +  ruleset_cis_arn = {
Love these ARN lookup  changes, thanks!

2020-07-01 19:39 UTC, bushong1 commented on main.tf
> +  name  = "${var.name_prefix}-inspector-event"
This would be a breaking change to existing users, and a major version bump, so we'd prefer not to change names for cosmetic reasons.

2020-09-02 13:25 UTC, mattjorg requested changes

2020-09-02 13:25 UTC, elijahmuha commented on README.md
> +* Inspector Rule Set ARN's proper to AWS Region - [list](https://docs.aws.amazon.com/inspector/latest/userguide/inspector_rules-arns.html#eu-west-1)
Remove the `#eu-west-1` portion of the link

2021-05-03 18:14 UTC, closed without merging